name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/**/*.keymap'
      - 'config/**/*.dtsi'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: ./.github/workflows/draw.yml
    with:
      keymap_patterns: "config/*.keymap"
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      draw_args: "adv360pro:'-k adv360pro'"
      json_path: keymap-drawer/layouts
      west_config_path: './config/'
      amend_commit: true